# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=50, unique=True, verbose_name='address'),
        ),
    ]
