# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160409_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
    ]
